# Copyright 2017 Eficent Business and IT Consulting Services, S.L.
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl.html).

from odoo import api, fields, models, _
from odoo.exceptions import UserError, ValidationError
from odoo.addons import decimal_precision as dp
from odoo.tools import float_compare


REQUEST_STATES = [
    ('draft', 'Draft'),
    ('open', 'In progress'),
    ('done', 'Done'),
    ('cancel', 'Cancelled')]


class StockRequest(models.Model):
    _name = "stock.request"
    _description = "Stock Request"
    _inherit = ['mail.thread', 'mail.activity.mixin']

    @api.model
    def default_get(self, fields):
        res = super(StockRequest, self).default_get(fields)
        warehouse = None
        if 'warehouse_id' not in res and res.get('company_id'):
            warehouse = self.env['stock.warehouse'].search(
                [('company_id', '=', res['company_id'])], limit=1)
        if warehouse:
            res['warehouse_id'] = warehouse.id
            res['location_id'] = warehouse.lot_stock_id.id
        return res

    @api.one
    @api.depends('product_id', 'product_uom', 'product_uom_qty')
    def _compute_product_qty(self):
        rounding_method = self._context.get('rounding_method', 'UP')
        self.product_qty = self.product_uom._compute_quantity(
            self.product_uom_qty, self.product_id.uom_id,
            rounding_method=rounding_method)

    name = fields.Char(
        'Name', copy=False, required=True, readonly=True,
        states={'draft': [('readonly', False)]},
        default=lambda self: self.env['ir.sequence'].next_by_code(
            'stock.request'))
    state = fields.Selection(selection=REQUEST_STATES, string='Status',
                             copy=False, default='draft', index=True,
                             readonly=True,
                             )
    warehouse_id = fields.Many2one(
        'stock.warehouse', 'Warehouse', readonly=False,
        ondelete="cascade", required=True)
    location_id = fields.Many2one(
        'stock.location', 'Location', readonly=False,
        ondelete="cascade", required=True)
    product_id = fields.Many2one(
        'product.product', 'Product', readonly=True,
        states={'draft': [('readonly', False)]},
        domain=[('type', 'in', ['product', 'consu'])], ondelete='cascade',
        required=True)
    product_uom = fields.Many2one(
        'product.uom', 'Product Unit of Measure', related='product_id.uom_id',
        readonly=True, required=True,
        states={'draft': [('readonly', False)]},
        default=lambda self: self._context.get('product_uom', False))
    product_uom_qty = fields.Float(
        'Quantity', digits=dp.get_precision('Product Unit of Measure'),
        states={'draft': [('readonly', False)]},
        readonly=True, required=True,
        help="Quantity, specified in the unit of measure indicated in the "
             "request.")
    product_qty = fields.Float(
        'Real Quantity', compute='_compute_product_qty',
        digits=0, store=True, readonly=True,
        help='Quantity in the default UoM of the product')
    procurement_group_id = fields.Many2one(
        'procurement.group', 'Procurement Group', copy=False, readonly=True,
        states={'draft': [('readonly', False)]},
        help="Moves created through this stock request will be put in this "
             "procurement group. If none is given, the moves generated by "
             "procurement rules will be grouped into one big picking.")
    company_id = fields.Many2one(
        'res.company', 'Company', required=True, readonly=True,
        states={'draft': [('readonly', False)]},
        default=lambda self: self.env['res.company']._company_default_get(
            'stock.request'))
    expected_date = fields.Datetime(
        'Expected date', default=fields.Datetime.now, index=True,
        required=True, readonly=True,
        states={'draft': [('readonly', False)]},
        help="Date when you expect to receive the goods.")
    picking_policy = fields.Selection([
        ('direct', 'Receive each product when available'),
        ('one', 'Receive all products at once')],
        string='Shipping Policy', required=True, readonly=True,
        states={'draft': [('readonly', False)]},
        default='direct')
    move_ids = fields.One2many('stock.move', 'stock_request_id',
                               string='Stock Moves', readonly=True)
    picking_ids = fields.One2many('stock.picking',
                                  compute='_compute_picking_ids',
                                  string='Pickings', readonly=True)
    qty_in_progress = fields.Float(
        'Qty In Progress', digits=dp.get_precision('Product Unit of Measure'),
        readonly=True, compute='_compute_qty',
        help="Quantity in progress.")
    qty_done = fields.Float(
        'Qty Done', digits=dp.get_precision('Product Unit of Measure'),
        readonly=True, compute='_compute_qty',
        help="Quantity completed")
    picking_count = fields.Integer(string='Delivery Orders',
                                   compute='_compute_picking_ids')
    route_id = fields.Many2one('stock.location.route', string='Route',
                               readonly=True,
                               states={'draft': [('readonly', False)]},
                               ondelete='restrict')

    @api.depends('picking_ids')
    def _compute_picking_ids(self):
        for request in self:
            request.picking_ids = [(6, 0, self.env['stock.picking'].search(
                [('group_id', '=', request.procurement_group_id.id),
                 ('state', '!=', 'cancel')]).ids)]
            request.picking_count = len(request.picking_ids)

    @api.depends('move_ids', 'move_ids.state')
    def _compute_qty(self):
        for request in self:
            rounding_method = self._context.get('rounding_method', 'UP')
            done_qty = sum(request.move_ids.filtered(
                lambda s: s.state == 'done').mapped('product_qty'))
            qty_in_progress = sum(request.move_ids.filtered(
                lambda s: s.state not in ['done', 'cancel']).mapped(
                'product_qty'))
            request.qty_done = request.product_id.uom_id._compute_quantity(
                done_qty, request.product_uom,
                rounding_method=rounding_method)
            request.qty_in_progress = \
                request.product_id.uom_id._compute_quantity(
                    qty_in_progress, request.product_uom,
                    rounding_method=rounding_method)

    @api.constrains('product_id')
    def _check_product_uom(self):
        ''' Check if the UoM has the same category as the
        product standard UoM '''
        if any(request.product_id.uom_id.category_id !=
                request.product_uom.category_id for request in self):
            raise ValidationError(
                _('You have to select a product unit of measure in the '
                  'same category than the default unit '
                  'of measure of the product'))

    @api.onchange('warehouse_id')
    def onchange_warehouse_id(self):
        """ Finds location id for changed warehouse. """
        if self.warehouse_id:
            self.location_id = self.warehouse_id.lot_stock_id.id
            self.company_id = self.warehouse_id.company_id

    @api.onchange('company_id')
    def onchange_company_id(self):
        """ Sets a default warehouse when the company is changed and limits
        the user selection of warehouses. """
        if self.company_id and (
                    not self.warehouse_id or
                        self.warehouse_id.company_id != self.company_id):
            self.warehouse_id = self.env['stock.warehouse'].search(
                [('company_id', '=', self.company_id.id)], limit=1)

        return {
            'domain': {
                'warehouse_id': [('company_id', '=', self.company_id.id)]}}

    @api.onchange('product_id')
    def onchange_product_id(self):
        if self.product_id:
            self.product_uom = self.product_id.uom_id.id
            return {
                'domain': {
                    'product_uom': [('category_id', '=',
                                     self.product_id.uom_id.category_id.id)]}}
        return {'domain': {'product_uom': []}}

    @api.multi
    def _action_confirm(self):
        self._action_launch_procurement_rule()
        self.state = 'open'

    @api.multi
    def action_confirm(self):
        self._action_confirm()
        return True

    def action_draft(self):
        self.state = 'draft'
        return True

    def action_cancel(self):
        self.mapped('move_ids').action_cancel()
        self.state = 'cancel'
        return True

    def _prepare_procurement_values(self, group_id=False):

        """ Prepare specific key for moves or other components that
        will be created from a procurement rule
        comming from a stock request. This method could be override
        in order to add other custom key that could be used in
        move/po creation.
        """
        return {
            'date_planned': self.expected_date,
            'warehouse_id': self.warehouse_id,
            'stock_request_id': self.id,
            'group_id': group_id or self.group_id,
            'route_ids': self.route_id,
        }

    def _prepare_procurement_group_values(self):
        return {
            'name': self.name,
            'move_type': self.picking_policy,
            'stock_request_id': self.id,
        }

    @api.multi
    def _action_launch_procurement_rule(self):
        """
        Launch procurement group run method with required/custom
        fields genrated by a
        stock request. procurement group will launch '_run_move',
        '_run_buy' or '_run_manufacture'
        depending on the stock request product rule.
        """
        precision = self.env['decimal.precision'].precision_get(
            'Product Unit of Measure')
        errors = []
        for request in self:
            if (
                request.state != 'draft' or not
                request.product_id.type in ('consu', 'product')
            ):
                continue
            qty = 0.0
            for move in request.move_ids.filtered(
                    lambda r: r.state != 'cancel'):
                qty += move.product_qty

            if float_compare(qty, request.product_qty,
                             precision_digits=precision) >= 0:
                continue
            if not request.procurement_group_id:
                request.procurement_group_id = self.env[
                    'procurement.group'].create(
                    self._prepare_procurement_group_values())
            values = request._prepare_procurement_values(
                group_id=request.procurement_group_id)
            try:
                self.env['procurement.group'].run(
                    request.product_id, request.product_uom_qty,
                    request.product_uom,
                    request.location_id, request.name,
                    request.name, values)
            except UserError as error:
                errors.append(error.name)
        if errors:
            raise UserError('\n'.join(errors))
        return True

    @api.multi
    def action_view_transfer(self):
        action = self.env.ref('stock.action_picking_tree_all').read()[0]

        pickings = self.mapped('picking_ids')
        if len(pickings) > 1:
            action['domain'] = [('id', 'in', pickings.ids)]
        elif pickings:
            action['views'] = [
                (self.env.ref('stock.view_picking_form').id, 'form')]
            action['res_id'] = pickings.id
        return action
